#!/bin/bash

# make sure there is at least one tmp directory so ls will not fail
mkdir -p sim/tmp.0

while : ; do # infinite loop
  # get a directory to work on
  for i in {1..10}; do
   # set d to the i-th last tmp directory
   d=$(ls -1dt sim/tmp.* | head -$i | tail -1)
   # is there exactly one file in it ?
   if [ "`ls -1 $d | wc -w`" == "1" ]; then
      if test -f $d/*.zip; then
         (cd $d; unzip *.zip; tail -1 top.zip >>top.sv)
      fi
      cp /labarc/TOP/Makefile $d
      (cd $d; timeout 3600 make sim 1>/dev/null 2>qq.log) &
   fi
  done
  sleep 2
done
