#!/bin/bash
# argument: cable number starting at 0

# make sure there is at least one tmp directory so ls will not fail
mkdir syn/tmp.0

while : ; do # infinite loop
  # get a directory to work on
  while ! d=$(curl -s lad:2525); do sleep 0.1; done
  if [[ $d = *[![:space:]]* ]]; then
    echo "sintesizing " $d
    cd $d
    if CABLE=$(expr $1 + 1) make > qq.log ; then
        timeout 300 quartus_stp -t /labarc/util/qr.tcl $1 > /dev/null 2>> qq.log
    fi
    echo "___________________pronto____________________" >> qq.log
    cd
  else
    sleep 1
  fi
done
